### PR TITLE
fix: include sysinfo.h to fix modern musl builds

### LINKED ISSUE #3: fails to build on gluon-next (openwrt-25.12)
I just tried to build this using gluon-next, which fails with this error:

```
HEAD is now at 8f1e556 daemon: fix missing ubus-subscribe
Generating formal git archive (apply .gitattributes rules)
Packing checkout...
touch /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.prepared_a049e518d9d7963c0bd117900991760f_6664517399ebbbc92a37c5bb081b5c53_check
. /mnt/site-2026.1.x/gluon-build/openwrt/include/shell.sh; zstdcat /mnt/site-2026.1.x/gluon-build/openwrt/dl/ffda-node-whisperer-1.tar.zst | tar -C /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1
touch /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.prepared_a049e518d9d7963c0bd117900991760f_6664517399ebbbc92a37c5bb081b5c53
rm -f /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.configured_*
rm -f /mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.ffda-node-whisperer_installed
(cd /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/./; if [ -x ./configure ]; then find /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/ -name config.guess | xargs -r chmod u+w; find /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/ -name config.guess | xargs -r -n1 cp --remove-destination /mnt/site-2026.1.x/gluon-build/openwrt/scripts/config.guess; find /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/ -name config.sub | xargs -r chmod u+w; find /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/ -name config.sub | xargs -r -n1 cp --remove-destination /mnt/site-2026.1.x/gluon-build/openwrt/scripts/config.sub; AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD="mipsel-openwrt-linux-musl-ld.bfd" NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mips16 -minterlink-mips16 " CPPFLAGS="-I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include/fortify " LDFLAGS="-L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/lib -L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/lib -fuse-ld=bfd -znow -zrelro "   ./configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-pc-linux-gnu --disable-dependency-tracking --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.built
touch /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.built_check
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include/fortify " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -mips16 -minterlink-mips16  -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/include/fortify " LDFLAGS="-L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/lib -L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/lib -fuse-ld=bfd -znow -zrelro " NL_LIB="libnl-tiny" NL_GENL_LIB="libnl-tiny" make -j1 -C /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/src AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1=ffda-node-whisperer-1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD="mipsel-openwrt-linux-musl-ld.bfd" NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CROSS="mipsel-openwrt-linux-musl-" ARCH="mipsel" ;
make[6]: Entering directory '/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/src'
mipsel-openwrt-linux-musl-gcc -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/libnl-tiny -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/libnl-tiny -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include -I/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/include/json-c -D_GNU_SOURCE -o node-whisperer daemon.c util.c information.c log.c ubus.c interface.c batadv.c -lubox -lubus -lblobmsg_json -lgluonutil -luci -L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib -lnl-tiny -lbatadv -L/mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib -ljson-c
cc1: note: someone does not honour COPTS correctly, passed 0 times
cc1: note: someone does not honour COPTS correctly, passed 0 times
cc1: note: someone does not honour COPTS correctly, passed 0 times
information.c: In function 'node_whisperer_information_uptime_collect':
information.c:120:15: error: implicit declaration of function 'sysinfo' [-Wimplicit-function-declaration]
  120 |         ret = sysinfo(&s_info);
      |               ^~~~~~~
cc1: note: someone does not honour COPTS correctly, passed 0 times
cc1: note: someone does not honour COPTS correctly, passed 0 times
cc1: note: someone does not honour COPTS correctly, passed 0 times
cc1: note: someone does not honour COPTS correctly, passed 0 times
make[6]: *** [Makefile:35: all] Error 1
make[6]: Leaving directory '/mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/src'
make[5]: *** [Makefile:47: /mnt/site-2026.1.x/gluon-build/openwrt/build_dir/target-mipsel_24kc_musl/ffda-node-whisperer-1/.built] Error 2
time: package/feeds/community/ffda-node-whisperer/compile#0.70#0.19#2.25
    ERROR: package/feeds/community/ffda-node-whisperer failed to build.
make[4]: *** [package/Makefile:188: package/feeds/community/ffda-node-whisperer/compile] Error 1
make[3]: *** [package/Makefile:182: /mnt/site-2026.1.x/gluon-build/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[2]: *** [/mnt/site-2026.1.x/gluon-build/openwrt/include/toplevel.mk:233: world] Error 2
make[1]: *** [Makefile:210: all] Error 2
make: *** [Makefile:147: build] Error 2
```

Any idea for this?

### PR DESCRIPTION
**Pull request by grische**
This should fix #3

### CODE REVIEW

**Comment by maurerle** [comment]
I can confirm that the build succeeds and the node-whisperer works with 25.12 using this branch:
https://github.com/freifunk-gluon/community-packages/tree/node-whisperer

I did also verify that this works with the node-whisperer app.
So this PR should be ready to review/merged.
